name: Bug report
about: Create a report to help us improve
title: 'Bug: (Your Bug name Here)'
labels: bug
assignees: 'eveeifyeve'
milestone: 'bug fixed'

body:
  - type: markdown
    attributes:
      value: |
        **Thanks for taking the time to report a bug!**
        **Please replace the placeholder texts below with the actual details.**

  - type: input
    id: rust-version
    attributes:
      label: Rust version
      description: What version of Rust are you using?
      placeholder: e.g., 1.55.0
    validations:
      required: true

  - type: input
    id: package-version
    attributes:
      label: Package version
      description: What version of the package are you using?
      placeholder: e.g., 0.1.0
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe the bug.
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: Please provide detailed steps for reproducing the issue.
      placeholder: Steps to reproduce the behavior.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: e.g., links to relevant issues, projects, or data
    validations:
      required: false